### ISSUE TITLE
[#3] 유저 리펙토링

### ISSUE THREAD

**Issue by takiki-web** [f-lab-edu/happy-delivery#34]
김정훈
1. contoller에 exception 수정 
2. 유저 삭제 
3. 중복 exception 메서드화

석지애
1. 전체적인 paramter 수정 command, request 수정
2. 주소 수정 삭제 부분 권한 삽입

공통
1. 프로젝트 방향성 , user 확장, 다른 도메인 생성 (화)
2. 세션 중복 처리 방안 aop 등(3월 5일 추가)

토, 일, 월, 회의진행
- 아침마다 comment로 진행사항 달고 회의진행시 구체적인 내용 토의
- 끝난 작업은 development 추가
- 월요일 저녁에 최종 회고 진행

**Comment by jiae5287** [comment]
1. 전체적인 paramter 수정 command, request 수정
2. 주소 수정 삭제 부분 권한 삽입

2개 모두 진행

**Comment by takiki-web** [comment]
1. controller에 ㄷxception 수정
2. 유저 삭제 api 생성
3. 중복 exception 메서드화 하려 했으나 지애님과 나의 코드가 달라 토의 필요

    Long userId = SessionUtil.getLoginId(httpSession);
    if (userId == null) {
      throw new NoUserIdException("유저 ID가 없습니다. 로그인 해주세요");
    }

    if (SessionUtil.getLoginId(httpSession) == null) {
      throw new NoUserIdException("로그인이 필요한 서비스입니다.");
    }

**Comment by takiki-web** [comment]
공통 1. [프로젝트 방향성 , user 확장, 다른 도메인 생성] 관련 회의

1. 유저 확장 ; 가게 찾기, 메뉴 보기, 장바구니 담기, 결제하기 -> 가게 Mdb, 메뉴 Mdb가 있으면 구현 가능

2. 가게 찾기는 가게 메모리 db에서 찾기

3. 메뉴 보기는 가게 가게 식별자의 메뉴 메모리 db에서 찾기

1. 가게 db, 메뉴 db에 무엇이 필요 한가?
 - 필요한 엔티티 구체화 해서 내일 토의(일)
 - read me 작성

**Comment by takiki-web** [comment]
<공통>
1. 가게 기능
        1. 가게 분류를 볼수 있다(석지애님)
        2. 가게 분류를 선택한다(석지애님)
        3. 가게 목록을 볼수 있다(석지애님)
        4. 가게를 선택한다(석지애님)
        5. 메뉴를 볼수 있다(김정훈님)
        6. 메뉴를 선택 한다(김정훈님)
        7. 선택한 메뉴를 장바구니에 담는다(김정훈님)
           * 큰줄기만 진행하고 나머지는 확장으로 진행

        1. 가게 Entity
            1. Id
            2. 가게명
            3. 가게분류
        2. 메뉴 Entity
            1. Id
            2. 메뉴명
            3. 메뉴 상세 내용
            4. 메뉴 가격

2.  질문사항 
    1. 배달지역 어떻게 설정 해야하나 ? 
    2. entity를 어디까지 구체화 해야 하나?
    3. userController, menuController등으로 세분화 해도 되는가?
