### ISSUE TITLE
[#7] 기능 추가

### ISSUE THREAD

**Issue by jiae5287** [f-lab-edu/happy-delivery#48]
< 가게 검색 기능 추가 >
가게 분류를 볼수 있다(석지애님)
가게 분류를 선택하면, 현재 주소에 맞게 가게 목록을 볼수 있다. (석지애님)
가게를 선택한다(석지애님)

< 메뉴 찾기 기능 추가 >
메뉴를 볼수 있다(김정훈님)
메뉴를 선택 한다(김정훈님)
선택한 메뉴를 장바구니에 담는다(김정훈님)

< 가게 Entity >
Id
가게명
가게분류

< 메뉴 Entity >
Id
메뉴명
메뉴 상세 내용
메뉴 가격

* 질문사항
배달지역 어떻게 설정 해야하나 ?

**Comment by takiki-web** [comment]
< 메뉴 찾기 기능 추가 >
1. 메뉴를 추가한다(김정훈님)
2. 메뉴를 볼수 있다(김정훈님)
3. 메뉴를 선택 한다(김정훈님)
4. 선택한 메뉴를 장바구니에 담는다(김정훈님)

**Comment by jiae5287** [comment]
<오늘 추가한 기능>
현재 주소 설정.
현재 주소로 설정되어 있으면 주소 삭제 불가능.
가게 분류 가져오기.

**Comment by jiae5287** [comment]
<추가한 기능>
가게 분류를 선택하면, 현재 주소에 맞게 가게 목록을 볼수 있다. (석지애님)
전반적인 리팩토링
